"""
更新数据
根据input/月业绩.xlsx数据生成描述性文字，不用改表头
"""

# 载入包
import pandas as pd
from docx import Document
from docx.oxml.ns import qn

# -------------------------------------------- 以下是代码 --------------------------------------------

# 新建word
document = Document()
document.styles['Normal'].font.name = 'Times New Roman'
document.styles['Normal']._element.rPr.rFonts.set(qn('w:eastAsia'), u'仿宋')
document.add_heading('主观多头', level=0)
index = pd.read_excel(r'input/业绩月数据.xlsx', sheet_name='主观多头')
B = index['月涨跌幅']
B_gt_0 = B > 0
n1 = B_gt_0.sum()
B_gt_0 = B < 0
n2 = B_gt_0.sum()
index.sort_values(by='月涨跌幅', ascending=False, inplace=True)
first_name = index.iloc[0, :]['产品名称']
first_score = "%.2f%%" % (index.iloc[0, :]['月涨跌幅'] * 100)
second_name = index.iloc[1, :]['产品名称']
second_score = "%.2f%%" % (index.iloc[1, :]['月涨跌幅'] * 100)
third_name = index.iloc[-2, :]['产品名称']
third_score = "%.2f%%" % (index.iloc[-2, :]['月涨跌幅'] * 100)
last_name = index.iloc[-1, :]['产品名称']
last_score = "%.2f%%" % (index.iloc[-1, :]['月涨跌幅'] * 100)
up = document.add_paragraph('股票多头策略中，')
if n1 == 0:
    first_score = "%.2f%%" % (index.iloc[0, :]['月涨跌幅'] * -100)
    last_score = "%.2f%%" % (index.iloc[-1, :]['月涨跌幅'] * -100)
    up.add_run('本月所有在架产品净值下跌。其中，')
    up.add_run(str(last_name))
    up.add_run('净值领跌，月跌')
    up.add_run(str(last_score))
    up.add_run('；')
    up.add_run(str(first_name))
    up.add_run('净值跌幅最小，月跌')
    up.add_run(str(first_score))
elif n2 == 0:  # 没有跌
    up.add_run('本月所有在架产品净值上涨。其中，')
    up.add_run(str(first_name))
    up.add_run('净值领涨，月涨')
    up.add_run(str(first_score))
    up.add_run('；其次为')
    up.add_run(str(second_name))
    up.add_run('，月涨')
    up.add_run(str(second_score))
    up.add_run('。')
    up.add_run(str(last_name))
    up.add_run('净值涨幅最小，月涨')
    up.add_run(str(last_score))
elif n2 == 1:  # 只有一个跌
    last_score = "%.2f%%" % (index.iloc[-1, :]['月涨跌幅'] * -100)
    up.add_run('本月仅')
    up.add_run(str(last_name))
    up.add_run('净值下跌，月跌')
    up.add_run(str(last_score))
    up.add_run('，其余在架产品净值均有所上涨。其中，')
    up.add_run(str(first_name))
    up.add_run('净值领涨，月涨')
    up.add_run(str(first_score))
    up.add_run('；其次为')
    up.add_run(str(second_name))
    up.add_run('，月涨')
    up.add_run(str(second_score))
elif n1 == 1:  # 只有一个涨
    last_score = "%.2f%%" % (index.iloc[-1, :]['月涨跌幅'] * -100)
    third_score = "%.2f%%" % (index.iloc[-2, :]['月涨跌幅'] * -100)
    up.add_run('本月仅')
    up.add_run(str(first_name))
    up.add_run('净值上涨，月涨')
    up.add_run(str(first_score))
    up.add_run('，其余在架产品净值均有所下跌。其中，')
    up.add_run(str(last_name))
    up.add_run('净值领跌，月跌')
    up.add_run(str(last_score))
    up.add_run('；其次为')
    up.add_run(str(third_name))
    up.add_run('，月跌')
    up.add_run(str(third_score))
elif n1 / (n1 + n2) >= 0.7:
    last_score = "%.2f%%" % (index.iloc[-1, :]['月涨跌幅'] * -100)
    up.add_run('本月在架产品净值多数上涨。其中，')
    up.add_run(str(first_name))
    up.add_run('净值领涨，月涨')
    up.add_run(str(first_score))
    up.add_run('；其次为')
    up.add_run(str(second_name))
    up.add_run('，月涨')
    up.add_run(str(second_score))
    up.add_run('。')
    up.add_run(str(last_name))
    up.add_run('净值领跌，月跌')
    up.add_run(str(last_score))
elif n2 / (n1 + n2) >= 0.7:
    last_score = "%.2f%%" % (index.iloc[-1, :]['月涨跌幅'] * -100)
    up.add_run('本月在架产品净值多数下跌。其中，')
    up.add_run(str(last_name))
    up.add_run('净值领跌，月跌')
    up.add_run(str(last_score))
    up.add_run('；')
    up.add_run(str(first_name))
    up.add_run('净值领涨，月涨')
    up.add_run(str(first_score))
else:
    last_score = "%.2f%%" % (index.iloc[-1, :]['月涨跌幅'] * -100)
    up.add_run('本月在架产品净值涨跌不一。其中，')
    up.add_run(str(first_name))
    up.add_run('净值领涨，月涨')
    up.add_run(str(first_score))
    up.add_run('；其次为')
    up.add_run(str(second_name))
    up.add_run('，月涨')
    up.add_run(str(second_score))
    up.add_run('。')
    up.add_run(str(last_name))
    up.add_run('净值领跌，月跌')
    up.add_run(str(last_score))
up.add_run('。周度来看，')
B = index['周涨跌幅']
B_gt_0 = B > 0
n1 = B_gt_0.sum()
B_gt_0 = B < 0
n2 = B_gt_0.sum()
index.sort_values(by='周涨跌幅', ascending=False, inplace=True)
first_name = index.iloc[0, :]['产品名称']
first_score = "%.2f%%" % (index.iloc[0, :]['周涨跌幅'] * 100)
last_name = index.iloc[-1, :]['产品名称']
last_score = "%.2f%%" % (index.iloc[-1, :]['周涨跌幅'] * 100)
if n1 == 0:
    first_score = "%.2f%%" % (index.iloc[0, :]['周涨跌幅'] * -100)
    last_score = "%.2f%%" % (index.iloc[-1, :]['周涨跌幅'] * -100)
    up.add_run('所有在架产品净值下跌，')
    up.add_run(str(last_name))
    up.add_run('净值领跌，周跌')
    up.add_run(str(last_score))
    up.add_run('；')
    up.add_run(str(first_name))
    up.add_run('净值跌幅最小，周跌')
    up.add_run(str(first_score))
elif n2 == 0:  # 没有跌
    up.add_run('所有在架产品净值上涨，')
    up.add_run(str(first_name))
    up.add_run('净值领涨，周涨')
    up.add_run(str(first_score))
    up.add_run('；')
    up.add_run(str(last_name))
    up.add_run('净值涨幅最小，周涨')
    up.add_run(str(last_score))
elif n2 == 1:  # 只有一个跌
    last_score = "%.2f%%" % (index.iloc[-1, :]['周涨跌幅'] * -100)
    up.add_run(str(first_name))
    up.add_run('净值领涨，周涨')
    up.add_run(str(first_score))
    up.add_run('；')
    up.add_run(str(last_name))
    up.add_run('净值下跌，周跌')
    up.add_run(str(last_score))
elif n1 == 1:  # 只有一个涨
    last_score = "%.2f%%" % (index.iloc[-1, :]['周涨跌幅'] * -100)
    up.add_run(str(last_name))
    up.add_run('净值领跌，周跌')
    up.add_run(str(last_score))
    up.add_run('；')
    up.add_run(str(first_name))
    up.add_run('净值上涨，周涨')
    up.add_run(str(first_score))
else:
    last_score = "%.2f%%" % (index.iloc[-1, :]['周涨跌幅'] * -100)
    up.add_run(str(first_name))
    up.add_run('净值领涨，周涨')
    up.add_run(str(first_score))
    up.add_run('；')
    up.add_run(str(last_name))
    up.add_run('净值领跌，周跌')
    up.add_run(str(last_score))
up.add_run('。')
document.add_heading('量化指增', level=0)
# 读取excel
index = pd.read_excel(r'input/业绩月数据.xlsx', sheet_name='量化指增')
B = index['月度超额']
B_gt_0 = B > 0
n1 = B_gt_0.sum()
B_gt_0 = B < 0
n2 = B_gt_0.sum()
index.sort_values(by='月度超额', ascending=False, inplace=True)
first_name = index.iloc[0, :]['产品名称']
first_score = "%.2f%%" % (index.iloc[0, :]['月度超额'] * 100)
second_name = index.iloc[1, :]['产品名称']
second_score = "%.2f%%" % (index.iloc[1, :]['月度超额'] * 100)
third_name = index.iloc[-2, :]['产品名称']
third_score = "%.2f%%" % (index.iloc[-2, :]['月度超额'] * 100)
last_name = index.iloc[-1, :]['产品名称']
last_score = "%.2f%%" % (index.iloc[-1, :]['月度超额'] * 100)
up = document.add_paragraph('指数增强策略中，')
if n1 == 0:
    up.add_run('本月所有在架产品超额为负。其中，')
    up.add_run(str(last_name))
    up.add_run('领跌，录得')
    up.add_run(str(last_score))
    up.add_run('的负超额；')
    up.add_run(str(first_name))
    up.add_run('跌幅最小，录得')
    up.add_run(str(first_score))
    up.add_run('的负超额')
elif n2 == 0:  # 没有跌
    up.add_run('本月所有在架产品超额为正。其中，')
    up.add_run(str(first_name))
    up.add_run('领涨，录得')
    up.add_run(str(first_score))
    up.add_run('的正超额；其次为')
    up.add_run(str(second_name))
    up.add_run('，录得')
    up.add_run(str(second_score))
    up.add_run('的正超额。')
    up.add_run(str(last_name))
    up.add_run('涨幅最小，录得正超额')
    up.add_run(str(last_score))
elif n2 == 1:  # 只有一个跌
    up.add_run('本月仅')
    up.add_run(str(last_name))
    up.add_run('录得')
    up.add_run(str(last_score))
    up.add_run('的负超额，其余在架产品超额为正。其中，')
    up.add_run(str(first_name))
    up.add_run('领涨，录得正超额')
    up.add_run(str(first_score))
    up.add_run('；其次为')
    up.add_run(str(second_name))
    up.add_run('，录得')
    up.add_run(str(second_score))
    up.add_run('的正超额')
elif n1 == 1:  # 只有一个涨
    up.add_run('本月仅')
    up.add_run(str(first_name))
    up.add_run('录得')
    up.add_run(str(first_score))
    up.add_run('的正超额，其余在架产品超额为负。其中，')
    up.add_run(str(last_name))
    up.add_run('领跌，录得负超额')
    up.add_run(str(last_score))
    up.add_run('；其次为')
    up.add_run(str(third_name))
    up.add_run('，录得')
    up.add_run(str(third_score))
    up.add_run('的负超额')
elif n1 / (n1 + n2) >= 0.7:
    up.add_run('本月在架产品超额多数上涨。其中，')
    up.add_run(str(first_name))
    up.add_run('领涨，录得')
    up.add_run(str(first_score))
    up.add_run('的正超额；')
    up.add_run(str(last_name))
    up.add_run('领跌，录得负超额')
    up.add_run(str(last_score))
elif n2 / (n1 + n2) >= 0.7:
    up.add_run('本月在架产品超额多数下跌。其中，')
    up.add_run(str(first_name))
    up.add_run('领涨，录得')
    up.add_run(str(first_score))
    up.add_run('的正超额；')
    up.add_run(str(last_name))
    up.add_run('领跌，录得负超额')
    up.add_run(str(last_score))
else:
    up.add_run('本月在架产品超额涨跌不一。其中，')
    up.add_run(str(first_name))
    up.add_run('领涨，录得')
    up.add_run(str(first_score))
    up.add_run('的正超额；')
    up.add_run(str(last_name))
    up.add_run('领跌，录得负超额')
    up.add_run(str(last_score))
up.add_run('。周度来看，本周')
B = index['上周超额']
B_gt_0 = B > 0
n1 = B_gt_0.sum()
B_gt_0 = B < 0
n2 = B_gt_0.sum()
index.sort_values(by='上周超额', ascending=False, inplace=True)
first_name = index.iloc[0, :]['产品名称']
first_score = "%.2f%%" % (index.iloc[0, :]['上周超额'] * 100)
last_name = index.iloc[-1, :]['产品名称']
last_score = "%.2f%%" % (index.iloc[-1, :]['上周超额'] * 100)
if n1 == 0:
    up.add_run(str(last_name))
    up.add_run('领跌，录得')
    up.add_run(str(last_score))
    up.add_run('的负超额；')
    up.add_run(str(first_name))
    up.add_run('跌幅最小，录得')
    up.add_run(str(first_score))
    up.add_run('的负超额')
elif n2 == 0:  # 没有跌
    up.add_run(str(first_name))
    up.add_run('领涨，录得')
    up.add_run(str(first_score))
    up.add_run('的正超额；')
    up.add_run(str(last_name))
    up.add_run('涨幅最小，录得正超额')
    up.add_run(str(last_score))
elif n2 == 1:  # 只有一个跌
    up.add_run(str(first_name))
    up.add_run('领涨，录得正超额')
    up.add_run(str(first_score))
    up.add_run('；')
    up.add_run(str(last_name))
    up.add_run('超额下跌，录得')
    up.add_run(str(last_score))
    up.add_run('的负超额')
elif n1 == 1:  # 只有一个涨
    up.add_run(str(last_name))
    up.add_run('领跌，录得负超额')
    up.add_run(str(last_score))
    up.add_run('；')
    up.add_run(str(first_name))
    up.add_run('超额上涨，录得')
    up.add_run(str(first_score))
    up.add_run('的正超额')
else:
    up.add_run(str(first_name))
    up.add_run('领涨，录得')
    up.add_run(str(first_score))
    up.add_run('的正超额；')
    up.add_run(str(last_name))
    up.add_run('领跌，录得负超额')
    up.add_run(str(last_score))
up.add_run('。')

document.add_heading('量化对冲', level=0)
index = pd.read_excel(r'input/业绩月数据.xlsx', sheet_name='量化对冲')
B = index['月涨跌幅']
B_gt_0 = B > 0
n1 = B_gt_0.sum()
B_gt_0 = B < 0
n2 = B_gt_0.sum()
index.sort_values(by='月涨跌幅', ascending=False, inplace=True)
first_name = index.iloc[0, :]['产品名称']
first_score = "%.2f%%" % (index.iloc[0, :]['月涨跌幅'] * 100)
second_name = index.iloc[1, :]['产品名称']
second_score = "%.2f%%" % (index.iloc[1, :]['月涨跌幅'] * 100)
third_name = index.iloc[-2, :]['产品名称']
third_score = "%.2f%%" % (index.iloc[-2, :]['月涨跌幅'] * 100)
last_name = index.iloc[-1, :]['产品名称']
last_score = "%.2f%%" % (index.iloc[-1, :]['月涨跌幅'] * 100)
up = document.add_paragraph('量化对冲策略中，')
if n1 == 0:
    first_score = "%.2f%%" % (index.iloc[0, :]['月涨跌幅'] * -100)
    last_score = "%.2f%%" % (index.iloc[-1, :]['月涨跌幅'] * -100)
    up.add_run('本月所有在架产品净值下跌。其中，')
    up.add_run(str(last_name))
    up.add_run('净值领跌，月跌')
    up.add_run(str(last_score))
    up.add_run('；')
    up.add_run(str(first_name))
    up.add_run('净值跌幅最小，月跌')
    up.add_run(str(first_score))
elif n2 == 0:  # 没有跌
    up.add_run('本月所有在架产品净值上涨。其中，')
    up.add_run(str(first_name))
    up.add_run('净值领涨，月涨')
    up.add_run(str(first_score))
    up.add_run('；其次为')
    up.add_run(str(second_name))
    up.add_run('，月涨')
    up.add_run(str(second_score))
    up.add_run('。')
    up.add_run(str(last_name))
    up.add_run('净值涨幅最小，月涨')
    up.add_run(str(last_score))
elif n2 == 1:  # 只有一个跌
    last_score = "%.2f%%" % (index.iloc[-1, :]['月涨跌幅'] * -100)
    up.add_run('本月仅')
    up.add_run(str(last_name))
    up.add_run('净值下跌，月跌')
    up.add_run(str(last_score))
    up.add_run('，其余在架产品净值均有所上涨。其中，')
    up.add_run(str(first_name))
    up.add_run('净值领涨，月涨')
    up.add_run(str(first_score))
    up.add_run('；其次为')
    up.add_run(str(second_name))
    up.add_run('，月涨')
    up.add_run(str(second_score))
elif n1 == 1:  # 只有一个涨
    last_score = "%.2f%%" % (index.iloc[-1, :]['月涨跌幅'] * -100)
    third_score = "%.2f%%" % (index.iloc[-2, :]['月涨跌幅'] * -100)
    up.add_run('本月仅')
    up.add_run(str(first_name))
    up.add_run('净值上涨，月涨')
    up.add_run(str(first_score))
    up.add_run('，其余在架产品净值均有所下跌。其中，')
    up.add_run(str(last_name))
    up.add_run('净值领跌，月跌')
    up.add_run(str(last_score))
    up.add_run('；其次为')
    up.add_run(str(third_name))
    up.add_run('，月跌')
    up.add_run(str(third_score))
else:
    last_score = "%.2f%%" % (index.iloc[-1, :]['月涨跌幅'] * -100)
    up.add_run('本月在架产品净值涨跌不一。其中，')
    up.add_run(str(first_name))
    up.add_run('净值领涨，月涨')
    up.add_run(str(first_score))
    up.add_run('；其次为')
    up.add_run(str(second_name))
    up.add_run('，月涨')
    up.add_run(str(second_score))
    up.add_run('。')
    up.add_run(str(last_name))
    up.add_run('净值领跌，月跌')
    up.add_run(str(last_score))
up.add_run('。周度来看，')
B = index['周涨跌幅']
B_gt_0 = B > 0
n1 = B_gt_0.sum()
B_gt_0 = B < 0
n2 = B_gt_0.sum()
index.sort_values(by='周涨跌幅', ascending=False, inplace=True)
first_name = index.iloc[0, :]['产品名称']
first_score = "%.2f%%" % (index.iloc[0, :]['周涨跌幅'] * 100)
last_name = index.iloc[-1, :]['产品名称']
last_score = "%.2f%%" % (index.iloc[-1, :]['周涨跌幅'] * 100)
if n1 == 0:
    first_score = "%.2f%%" % (index.iloc[0, :]['周涨跌幅'] * -100)
    last_score = "%.2f%%" % (index.iloc[-1, :]['周涨跌幅'] * -100)
    up.add_run('所有在架产品净值下跌，')
    up.add_run(str(last_name))
    up.add_run('净值领跌，周跌')
    up.add_run(str(last_score))
    up.add_run('；')
    up.add_run(str(first_name))
    up.add_run('净值跌幅最小，周跌')
    up.add_run(str(first_score))
elif n2 == 0:  # 没有跌
    up.add_run('所有在架产品净值上涨，')
    up.add_run(str(first_name))
    up.add_run('净值领涨，周涨')
    up.add_run(str(first_score))
    up.add_run('；')
    up.add_run(str(last_name))
    up.add_run('净值涨幅最小，周涨')
    up.add_run(str(last_score))
elif n2 == 1:  # 只有一个跌
    last_score = "%.2f%%" % (index.iloc[-1, :]['周涨跌幅'] * -100)
    up.add_run(str(first_name))
    up.add_run('净值领涨，周涨')
    up.add_run(str(first_score))
    up.add_run('；')
    up.add_run(str(last_name))
    up.add_run('净值下跌，周跌')
    up.add_run(str(last_score))
elif n1 == 1:  # 只有一个涨
    last_score = "%.2f%%" % (index.iloc[-1, :]['周涨跌幅'] * -100)
    up.add_run(str(last_name))
    up.add_run('净值领跌，周跌')
    up.add_run(str(last_score))
    up.add_run('；')
    up.add_run(str(first_name))
    up.add_run('净值上涨，周涨')
    up.add_run(str(first_score))
else:
    last_score = "%.2f%%" % (index.iloc[-1, :]['周涨跌幅'] * -100)
    up.add_run(str(first_name))
    up.add_run('净值领涨，周涨')
    up.add_run(str(first_score))
    up.add_run('；')
    up.add_run(str(last_name))
    up.add_run('净值领跌，周跌')
    up.add_run(str(last_score))
up.add_run('。')
document.add_heading('FOF/TOF', level=0)
index = pd.read_excel(r'input/业绩月数据.xlsx', sheet_name='FOF')
B = index['月涨跌幅']
B_gt_0 = B > 0
n1 = B_gt_0.sum()
B_gt_0 = B < 0
n2 = B_gt_0.sum()
index.sort_values(by='月涨跌幅', ascending=False, inplace=True)
first_name = index.iloc[0, :]['产品名称']
first_score = "%.2f%%" % (index.iloc[0, :]['月涨跌幅'] * 100)
second_name = index.iloc[1, :]['产品名称']
second_score = "%.2f%%" % (index.iloc[1, :]['月涨跌幅'] * 100)
third_name = index.iloc[-2, :]['产品名称']
third_score = "%.2f%%" % (index.iloc[-2, :]['月涨跌幅'] * 100)
last_name = index.iloc[-1, :]['产品名称']
last_score = "%.2f%%" % (index.iloc[-1, :]['月涨跌幅'] * 100)
up = document.add_paragraph('FOF/TOF中，')
if n1 == 0:
    first_score = "%.2f%%" % (index.iloc[0, :]['月涨跌幅'] * -100)
    last_score = "%.2f%%" % (index.iloc[-1, :]['月涨跌幅'] * -100)
    up.add_run('本月所有在架产品净值下跌。其中，')
    up.add_run(str(last_name))
    up.add_run('净值领跌，月跌')
    up.add_run(str(last_score))
    up.add_run('；')
    up.add_run(str(first_name))
    up.add_run('净值跌幅最小，月跌')
    up.add_run(str(first_score))
elif n2 == 0:  # 没有跌
    up.add_run('本月所有在架产品净值上涨。其中，')
    up.add_run(str(first_name))
    up.add_run('净值领涨，月涨')
    up.add_run(str(first_score))
    up.add_run('；其次为')
    up.add_run(str(second_name))
    up.add_run('，月涨')
    up.add_run(str(second_score))
    up.add_run('。')
    up.add_run(str(last_name))
    up.add_run('净值涨幅最小，月涨')
    up.add_run(str(last_score))
elif n2 == 1:  # 只有一个跌
    last_score = "%.2f%%" % (index.iloc[-1, :]['月涨跌幅'] * -100)
    up.add_run('本月仅')
    up.add_run(str(last_name))
    up.add_run('净值下跌，月跌')
    up.add_run(str(last_score))
    up.add_run('，其余在架产品净值均有所上涨。其中，')
    up.add_run(str(first_name))
    up.add_run('净值领涨，月涨')
    up.add_run(str(first_score))
    up.add_run('；其次为')
    up.add_run(str(second_name))
    up.add_run('，月涨')
    up.add_run(str(second_score))
elif n1 == 1:  # 只有一个涨
    last_score = "%.2f%%" % (index.iloc[-1, :]['月涨跌幅'] * -100)
    third_score = "%.2f%%" % (index.iloc[-2, :]['月涨跌幅'] * -100)
    up.add_run('本月仅')
    up.add_run(str(first_name))
    up.add_run('净值上涨，月涨')
    up.add_run(str(first_score))
    up.add_run('，其余在架产品净值均有所下跌。其中，')
    up.add_run(str(last_name))
    up.add_run('净值领跌，月跌')
    up.add_run(str(last_score))
    up.add_run('；其次为')
    up.add_run(str(third_name))
    up.add_run('，月跌')
    up.add_run(str(third_score))
elif n1 / (n1 + n2) >= 0.7:
    last_score = "%.2f%%" % (index.iloc[-1, :]['月涨跌幅'] * -100)
    up.add_run('本月在架产品净值多数上涨。其中，')
    up.add_run(str(first_name))
    up.add_run('净值领涨，月涨')
    up.add_run(str(first_score))
    up.add_run('；其次为')
    up.add_run(str(second_name))
    up.add_run('，月涨')
    up.add_run(str(second_score))
    up.add_run('。')
    up.add_run(str(last_name))
    up.add_run('净值领跌，月跌')
    up.add_run(str(last_score))
elif n2 / (n1 + n2) >= 0.7:
    last_score = "%.2f%%" % (index.iloc[-1, :]['月涨跌幅'] * -100)
    up.add_run('本月在架产品净值多数下跌。其中，')
    up.add_run(str(last_name))
    up.add_run('净值领跌，月跌')
    up.add_run(str(last_score))
    up.add_run('；')
    up.add_run(str(first_name))
    up.add_run('净值领涨，月涨')
    up.add_run(str(first_score))
else:
    last_score = "%.2f%%" % (index.iloc[-1, :]['月涨跌幅'] * -100)
    up.add_run('本月在架产品净值涨跌不一。其中，')
    up.add_run(str(first_name))
    up.add_run('净值领涨，月涨')
    up.add_run(str(first_score))
    up.add_run('；其次为')
    up.add_run(str(second_name))
    up.add_run('，月涨')
    up.add_run(str(second_score))
    up.add_run('。')
    up.add_run(str(last_name))
    up.add_run('净值领跌，月跌')
    up.add_run(str(last_score))
up.add_run('。周度来看，')
B = index['周涨跌幅']
B_gt_0 = B > 0
n1 = B_gt_0.sum()
B_gt_0 = B < 0
n2 = B_gt_0.sum()
index.sort_values(by='周涨跌幅', ascending=False, inplace=True)
first_name = index.iloc[0, :]['产品名称']
first_score = "%.2f%%" % (index.iloc[0, :]['周涨跌幅'] * 100)
last_name = index.iloc[-1, :]['产品名称']
last_score = "%.2f%%" % (index.iloc[-1, :]['周涨跌幅'] * 100)
if n1 == 0:
    first_score = "%.2f%%" % (index.iloc[0, :]['周涨跌幅'] * -100)
    last_score = "%.2f%%" % (index.iloc[-1, :]['周涨跌幅'] * -100)
    up.add_run('所有在架产品净值下跌，')
    up.add_run(str(last_name))
    up.add_run('净值领跌，周跌')
    up.add_run(str(last_score))
    up.add_run('；')
    up.add_run(str(first_name))
    up.add_run('净值跌幅最小，周跌')
    up.add_run(str(first_score))
elif n2 == 0:  # 没有跌
    up.add_run('所有在架产品净值上涨，')
    up.add_run(str(first_name))
    up.add_run('净值领涨，周涨')
    up.add_run(str(first_score))
    up.add_run('；')
    up.add_run(str(last_name))
    up.add_run('净值涨幅最小，周涨')
    up.add_run(str(last_score))
elif n2 == 1:  # 只有一个跌
    last_score = "%.2f%%" % (index.iloc[-1, :]['周涨跌幅'] * -100)
    up.add_run(str(first_name))
    up.add_run('净值领涨，周涨')
    up.add_run(str(first_score))
    up.add_run('；')
    up.add_run(str(last_name))
    up.add_run('净值下跌，周跌')
    up.add_run(str(last_score))
elif n1 == 1:  # 只有一个涨
    last_score = "%.2f%%" % (index.iloc[-1, :]['周涨跌幅'] * -100)
    up.add_run(str(last_name))
    up.add_run('净值领跌，周跌')
    up.add_run(str(last_score))
    up.add_run('；')
    up.add_run(str(first_name))
    up.add_run('净值上涨，周涨')
    up.add_run(str(first_score))
else:
    last_score = "%.2f%%" % (index.iloc[-1, :]['周涨跌幅'] * -100)
    up.add_run(str(first_name))
    up.add_run('净值领涨，周涨')
    up.add_run(str(first_score))
    up.add_run('；')
    up.add_run(str(last_name))
    up.add_run('净值领跌，周跌')
    up.add_run(str(last_score))
up.add_run('。')
document.add_heading('固定收益', level=0)
index = pd.read_excel(r'input/业绩月数据.xlsx', sheet_name='固定收益')
B = index['月涨跌幅']
B_gt_0 = B > 0
n1 = B_gt_0.sum()
B_gt_0 = B < 0
n2 = B_gt_0.sum()
index.sort_values(by='月涨跌幅', ascending=False, inplace=True)
first_name = index.iloc[0, :]['产品名称']
first_score = "%.2f%%" % (index.iloc[0, :]['月涨跌幅'] * 100)
second_name = index.iloc[1, :]['产品名称']
second_score = "%.2f%%" % (index.iloc[1, :]['月涨跌幅'] * 100)
third_name = index.iloc[-2, :]['产品名称']
third_score = "%.2f%%" % (index.iloc[-2, :]['月涨跌幅'] * 100)
last_name = index.iloc[-1, :]['产品名称']
last_score = "%.2f%%" % (index.iloc[-1, :]['月涨跌幅'] * 100)
up = document.add_paragraph('固定收益及固收+中，')
if n1 == 0:
    first_score = "%.2f%%" % (index.iloc[0, :]['月涨跌幅'] * -100)
    last_score = "%.2f%%" % (index.iloc[-1, :]['月涨跌幅'] * -100)
    up.add_run('本月所有在架产品净值下跌。其中，')
    up.add_run(str(last_name))
    up.add_run('净值领跌，月跌')
    up.add_run(str(last_score))
    up.add_run('；')
    up.add_run(str(first_name))
    up.add_run('净值跌幅最小，月跌')
    up.add_run(str(first_score))
elif n2 == 0:  # 没有跌
    up.add_run('本月所有在架产品净值上涨。其中，')
    up.add_run(str(first_name))
    up.add_run('净值领涨，月涨')
    up.add_run(str(first_score))
    up.add_run('；其次为')
    up.add_run(str(second_name))
    up.add_run('，月涨')
    up.add_run(str(second_score))
    up.add_run('。')
    up.add_run(str(last_name))
    up.add_run('净值涨幅最小，月涨')
    up.add_run(str(last_score))
elif n2 == 1:  # 只有一个跌
    last_score = "%.2f%%" % (index.iloc[-1, :]['月涨跌幅'] * -100)
    up.add_run('本月仅')
    up.add_run(str(last_name))
    up.add_run('净值下跌，月跌')
    up.add_run(str(last_score))
    up.add_run('，其余在架产品净值均有所上涨。其中，')
    up.add_run(str(first_name))
    up.add_run('净值领涨，月涨')
    up.add_run(str(first_score))
    up.add_run('；其次为')
    up.add_run(str(second_name))
    up.add_run('，月涨')
    up.add_run(str(second_score))
elif n1 == 1:  # 只有一个涨
    last_score = "%.2f%%" % (index.iloc[-1, :]['月涨跌幅'] * -100)
    third_score = "%.2f%%" % (index.iloc[-2, :]['月涨跌幅'] * -100)
    up.add_run('本月仅')
    up.add_run(str(first_name))
    up.add_run('净值上涨，月涨')
    up.add_run(str(first_score))
    up.add_run('，其余在架产品净值均有所下跌。其中，')
    up.add_run(str(last_name))
    up.add_run('净值领跌，月跌')
    up.add_run(str(last_score))
    up.add_run('；其次为')
    up.add_run(str(third_name))
    up.add_run('，月跌')
    up.add_run(str(third_score))
elif n1 / (n1 + n2) >= 0.7:
    last_score = "%.2f%%" % (index.iloc[-1, :]['月涨跌幅'] * -100)
    up.add_run('本月在架产品净值多数上涨。其中，')
    up.add_run(str(first_name))
    up.add_run('净值领涨，月涨')
    up.add_run(str(first_score))
    up.add_run('；其次为')
    up.add_run(str(second_name))
    up.add_run('，月涨')
    up.add_run(str(second_score))
    up.add_run('。')
    up.add_run(str(last_name))
    up.add_run('净值领跌，月跌')
    up.add_run(str(last_score))
elif n2 / (n1 + n2) >= 0.7:
    last_score = "%.2f%%" % (index.iloc[-1, :]['月涨跌幅'] * -100)
    up.add_run('本月在架产品净值多数下跌。其中，')
    up.add_run(str(last_name))
    up.add_run('净值领跌，月跌')
    up.add_run(str(last_score))
    up.add_run('；')
    up.add_run(str(first_name))
    up.add_run('净值领涨，月涨')
    up.add_run(str(first_score))
else:
    last_score = "%.2f%%" % (index.iloc[-1, :]['月涨跌幅'] * -100)
    up.add_run('本月在架产品净值涨跌不一。其中，')
    up.add_run(str(first_name))
    up.add_run('净值领涨，月涨')
    up.add_run(str(first_score))
    up.add_run('；其次为')
    up.add_run(str(second_name))
    up.add_run('，月涨')
    up.add_run(str(second_score))
    up.add_run('。')
    up.add_run(str(last_name))
    up.add_run('净值领跌，月跌')
    up.add_run(str(last_score))
up.add_run('。周度来看，')
B = index['周涨跌幅']
B_gt_0 = B > 0
n1 = B_gt_0.sum()
B_gt_0 = B < 0
n2 = B_gt_0.sum()
index.sort_values(by='周涨跌幅', ascending=False, inplace=True)
first_name = index.iloc[0, :]['产品名称']
first_score = "%.2f%%" % (index.iloc[0, :]['周涨跌幅'] * 100)
last_name = index.iloc[-1, :]['产品名称']
last_score = "%.2f%%" % (index.iloc[-1, :]['周涨跌幅'] * 100)
if n1 == 0:
    first_score = "%.2f%%" % (index.iloc[0, :]['周涨跌幅'] * -100)
    last_score = "%.2f%%" % (index.iloc[-1, :]['周涨跌幅'] * -100)
    up.add_run('所有在架产品净值下跌，')
    up.add_run(str(last_name))
    up.add_run('净值领跌，周跌')
    up.add_run(str(last_score))
    up.add_run('；')
    up.add_run(str(first_name))
    up.add_run('净值跌幅最小，周跌')
    up.add_run(str(first_score))
elif n2 == 0:  # 没有跌
    up.add_run('所有在架产品净值上涨，')
    up.add_run(str(first_name))
    up.add_run('净值领涨，周涨')
    up.add_run(str(first_score))
    up.add_run('；')
    up.add_run(str(last_name))
    up.add_run('净值涨幅最小，周涨')
    up.add_run(str(last_score))
elif n2 == 1:  # 只有一个跌
    last_score = "%.2f%%" % (index.iloc[-1, :]['周涨跌幅'] * -100)
    up.add_run(str(first_name))
    up.add_run('净值领涨，周涨')
    up.add_run(str(first_score))
    up.add_run('；')
    up.add_run(str(last_name))
    up.add_run('净值下跌，周跌')
    up.add_run(str(last_score))
elif n1 == 1:  # 只有一个涨
    last_score = "%.2f%%" % (index.iloc[-1, :]['周涨跌幅'] * -100)
    up.add_run(str(last_name))
    up.add_run('净值领跌，周跌')
    up.add_run(str(last_score))
    up.add_run('；')
    up.add_run(str(first_name))
    up.add_run('净值上涨，周涨')
    up.add_run(str(first_score))
else:
    last_score = "%.2f%%" % (index.iloc[-1, :]['周涨跌幅'] * -100)
    up.add_run(str(first_name))
    up.add_run('净值领涨，周涨')
    up.add_run(str(first_score))
    up.add_run('；')
    up.add_run(str(last_name))
    up.add_run('净值领跌，周跌')
    up.add_run(str(last_score))
up.add_run('。')
document.add_heading('CTA', level=0)
index = pd.read_excel(r'input/业绩月数据.xlsx', sheet_name='CTA')
B = index['月涨跌幅']
B_gt_0 = B > 0
n1 = B_gt_0.sum()
B_gt_0 = B < 0
n2 = B_gt_0.sum()
index.sort_values(by='月涨跌幅', ascending=False, inplace=True)
first_name = index.iloc[0, :]['产品名称']
first_score = "%.2f%%" % (index.iloc[0, :]['月涨跌幅'] * 100)
second_name = index.iloc[1, :]['产品名称']
second_score = "%.2f%%" % (index.iloc[1, :]['月涨跌幅'] * 100)
third_name = index.iloc[-2, :]['产品名称']
third_score = "%.2f%%" % (index.iloc[-2, :]['月涨跌幅'] * 100)
last_name = index.iloc[-1, :]['产品名称']
last_score = "%.2f%%" % (index.iloc[-1, :]['月涨跌幅'] * 100)
up = document.add_paragraph('CTA 及混合策略中，')
if n1 == 0:
    first_score = "%.2f%%" % (index.iloc[0, :]['月涨跌幅'] * -100)
    last_score = "%.2f%%" % (index.iloc[-1, :]['月涨跌幅'] * -100)
    up.add_run('本月所有在架产品净值下跌。其中，')
    up.add_run(str(last_name))
    up.add_run('净值领跌，月跌')
    up.add_run(str(last_score))
    up.add_run('；')
    up.add_run(str(first_name))
    up.add_run('净值跌幅最小，月跌')
    up.add_run(str(first_score))
elif n2 == 0:  # 没有跌
    up.add_run('本月所有在架产品净值上涨。其中，')
    up.add_run(str(first_name))
    up.add_run('净值领涨，月涨')
    up.add_run(str(first_score))
    up.add_run('；其次为')
    up.add_run(str(second_name))
    up.add_run('，月涨')
    up.add_run(str(second_score))
    up.add_run('。')
    up.add_run(str(last_name))
    up.add_run('净值涨幅最小，月涨')
    up.add_run(str(last_score))
elif n2 == 1:  # 只有一个跌
    last_score = "%.2f%%" % (index.iloc[-1, :]['月涨跌幅'] * -100)
    up.add_run('本月仅')
    up.add_run(str(last_name))
    up.add_run('净值下跌，月跌')
    up.add_run(str(last_score))
    up.add_run('，其余在架产品净值均有所上涨。其中，')
    up.add_run(str(first_name))
    up.add_run('净值领涨，月涨')
    up.add_run(str(first_score))
    up.add_run('；其次为')
    up.add_run(str(second_name))
    up.add_run('，月涨')
    up.add_run(str(second_score))
elif n1 == 1:  # 只有一个涨
    last_score = "%.2f%%" % (index.iloc[-1, :]['月涨跌幅'] * -100)
    third_score = "%.2f%%" % (index.iloc[-2, :]['月涨跌幅'] * -100)
    up.add_run('本月仅')
    up.add_run(str(first_name))
    up.add_run('净值上涨，月涨')
    up.add_run(str(first_score))
    up.add_run('，其余在架产品净值均有所下跌。其中，')
    up.add_run(str(last_name))
    up.add_run('净值领跌，月跌')
    up.add_run(str(last_score))
    up.add_run('；其次为')
    up.add_run(str(third_name))
    up.add_run('，月跌')
    up.add_run(str(third_score))
elif n1 / (n1 + n2) >= 0.7:
    last_score = "%.2f%%" % (index.iloc[-1, :]['月涨跌幅'] * -100)
    up.add_run('本月在架产品净值多数上涨。其中，')
    up.add_run(str(first_name))
    up.add_run('净值领涨，月涨')
    up.add_run(str(first_score))
    up.add_run('；其次为')
    up.add_run(str(second_name))
    up.add_run('，月涨')
    up.add_run(str(second_score))
    up.add_run('。')
    up.add_run(str(last_name))
    up.add_run('净值领跌，月跌')
    up.add_run(str(last_score))
elif n2 / (n1 + n2) >= 0.7:
    last_score = "%.2f%%" % (index.iloc[-1, :]['月涨跌幅'] * -100)
    up.add_run('本月在架产品净值多数下跌。其中，')
    up.add_run(str(last_name))
    up.add_run('净值领跌，月跌')
    up.add_run(str(last_score))
    up.add_run('；')
    up.add_run(str(first_name))
    up.add_run('净值领涨，月涨')
    up.add_run(str(first_score))
else:
    last_score = "%.2f%%" % (index.iloc[-1, :]['月涨跌幅'] * -100)
    up.add_run('本月在架产品净值涨跌不一。其中，')
    up.add_run(str(first_name))
    up.add_run('净值领涨，月涨')
    up.add_run(str(first_score))
    up.add_run('；其次为')
    up.add_run(str(second_name))
    up.add_run('，月涨')
    up.add_run(str(second_score))
    up.add_run('。')
    up.add_run(str(last_name))
    up.add_run('净值领跌，月跌')
    up.add_run(str(last_score))
up.add_run('。周度来看，')
B = index['周涨跌幅']
B_gt_0 = B > 0
n1 = B_gt_0.sum()
B_gt_0 = B < 0
n2 = B_gt_0.sum()
index.sort_values(by='周涨跌幅', ascending=False, inplace=True)
first_name = index.iloc[0, :]['产品名称']
first_score = "%.2f%%" % (index.iloc[0, :]['周涨跌幅'] * 100)
last_name = index.iloc[-1, :]['产品名称']
last_score = "%.2f%%" % (index.iloc[-1, :]['周涨跌幅'] * 100)
if n1 == 0:
    first_score = "%.2f%%" % (index.iloc[0, :]['周涨跌幅'] * -100)
    last_score = "%.2f%%" % (index.iloc[-1, :]['周涨跌幅'] * -100)
    up.add_run('所有在架产品净值下跌，')
    up.add_run(str(last_name))
    up.add_run('净值领跌，周跌')
    up.add_run(str(last_score))
    up.add_run('；')
    up.add_run(str(first_name))
    up.add_run('净值跌幅最小，周跌')
    up.add_run(str(first_score))
elif n2 == 0:  # 没有跌
    up.add_run('所有在架产品净值上涨，')
    up.add_run(str(first_name))
    up.add_run('净值领涨，周涨')
    up.add_run(str(first_score))
    up.add_run('；')
    up.add_run(str(last_name))
    up.add_run('净值涨幅最小，周涨')
    up.add_run(str(last_score))
elif n2 == 1:  # 只有一个跌
    last_score = "%.2f%%" % (index.iloc[-1, :]['周涨跌幅'] * -100)
    up.add_run(str(first_name))
    up.add_run('净值领涨，周涨')
    up.add_run(str(first_score))
    up.add_run('；')
    up.add_run(str(last_name))
    up.add_run('净值下跌，周跌')
    up.add_run(str(last_score))
elif n1 == 1:  # 只有一个涨
    last_score = "%.2f%%" % (index.iloc[-1, :]['周涨跌幅'] * -100)
    up.add_run(str(last_name))
    up.add_run('净值领跌，周跌')
    up.add_run(str(last_score))
    up.add_run('；')
    up.add_run(str(first_name))
    up.add_run('净值上涨，周涨')
    up.add_run(str(first_score))
else:
    last_score = "%.2f%%" % (index.iloc[-1, :]['周涨跌幅'] * -100)
    up.add_run(str(first_name))
    up.add_run('净值领涨，周涨')
    up.add_run(str(first_score))
    up.add_run('；')
    up.add_run(str(last_name))
    up.add_run('净值领跌，周跌')
    up.add_run(str(last_score))
up.add_run('。')
# 输出word
document.save('output/业绩月报告.docx')
